### ISSUE TITLE
Crash when reversing while tth hash is being calculated

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1002]
Do this:
- `dd if=/dev/zero of=/tmp/test.bin bs=1024 count=1MB`
- `openmsx -ext ide -hda /tmp/test.bin`
- and directly start hitting PgUp right after openMSX started up.

This gives me the following assertion failure:

```
openmsx: src/utils/stl.hh:146: ITER find_if_unguarded(ITER, ITER, PRED) [with ITER = __gnu_cxx::__normal_iterator<std::unique_ptr<openmsx::MSXMotherBoard>*, std::vector<std::unique_ptr<openmsx::MSXMotherBoard> > >; PRED = openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, openmsx::Reactor::Board)::<lambda(std::vector<std::unique_ptr<openmsx::MSXMotherBoard> >::value_type&)>]: Assertion `first != last' failed.
Aborted (core dumped)
```

Some stack tracing:

```
#0  0x00007fbf752bb507 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007fbf752bc8da in __GI_abort () at abort.c:89
#2  0x00007fbf752b459d in __assert_fail_base (
    fmt=0x7fbf753f16b8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7837dc "first != last", 
    file=file@entry=0x7837cb "src/utils/stl.hh", line=line@entry=146, 
    function=function@entry=0x7947a0 <__gnu_cxx::__normal_iterator<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >*, std::vector<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >, std::allocator<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> > > > > find_if_unguarded<__gnu_cxx::__normal_iterator<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >*, std::vector<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >, std::allocator<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> > > > >, openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >)::{lambda(std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >&)#1}>(openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >)::{lambda(std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >&)#1}, openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, std::uniqu---Type <return> to continue, or q <return> to quit---
e_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >)::{lambda(std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >&)#1}, openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >)::{lambda(std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >&)#1})::__PRETTY_FUNCTION__> "ITER find_if_unguarded(ITER, ITER, PRED) [with ITER = __gnu_cxx::__normal_iterator<std::unique_ptr<openmsx::MSXMotherBoard>*, std::vector<std::unique_ptr<openmsx::MSXMotherBoard> > >; PRED = openmsx::"...) at assert.c:92
#3  0x00007fbf752b4652 in __GI___assert_fail (
    assertion=assertion@entry=0x7837dc "first != last", 
    file=file@entry=0x7837cb "src/utils/stl.hh", line=line@entry=146, 
    function=function@entry=0x7947a0 <__gnu_cxx::__normal_iterator<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >*, std::vector<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >, std::allocator<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> > > > > find_if_unguarded<__gnu_cxx::__normal_iterator<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >*, std::vector<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >, std::allocator<std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> > > > >, openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >)::{lambda(std::uniqu---Type <return> to continue, or q <return> to quit---
e_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >&)#1}>(openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >)::{lambda(std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >&)#1}, openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >)::{lambda(std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >&)#1}, openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >)::{lambda(std::unique_ptr<openmsx::MSXMotherBoard, std::default_delete<openmsx::MSXMotherBoard> >&)#1})::__PRETTY_FUNCTION__> "ITER find_if_unguarded(ITER, ITER, PRED) [with ITER = __gnu_cxx::__normal_iterator<std::unique_ptr<openmsx::MSXMotherBoard>*, std::vector<std::unique_ptr<openmsx::MSXMotherBoard> > >; PRED = openmsx::"...) at assert.c:101
#4  0x000000000044deb5 in find_if_unguarded<__gnu_cxx::__normal_iterator<std::unique_ptr<openmsx::MSXMotherBoard>*, std::vector<std::unique_ptr<openmsx::MSXMotherBoard> > >, openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, openmsx::Reactor::Board)::<lambda(std::vector<std::unique_ptr<openmsx::MSXMotherBoard> >::value_type&)> > (pred=..., last=..., 
    first=std::unique_ptr<openmsx::MSXMotherBoard> containing 0x5941170)
    at src/utils/stl.hh:146
#5  find_if_unguarded<std::vector<std::unique_ptr<openmsx::MSXMotherBoard> >, openmsx::Reactor::replaceBoard(openmsx::MSXMotherBoard&, openmsx::Reactor::Board):---Type <return> to continue, or q <return> to quit---
:<lambda(std::vector<std::unique_ptr<openmsx::MSXMotherBoard> >::value_type&)> > (pred=..., range=std::vector of length 2, capacity 2 = {...})
    at src/utils/stl.hh:155
#6  openmsx::Reactor::replaceBoard (this=this@entry=0x7ffe8dc8f120, oldBoard_=
    ..., newBoard_=std::unique_ptr<openmsx::MSXMotherBoard> containing 0x0)
    at src/Reactor.cc:374
#7  0x0000000000454b01 in openmsx::ReverseManager::goTo (
    this=this@entry=0x18bb950, target=..., novideo=<optimized out>, hist=..., 
    sameTimeLine=sameTimeLine@entry=true) at src/ReverseManager.cc:494
#8  0x00000000004550b4 in openmsx::ReverseManager::goTo (
    this=this@entry=0x18bb950, target=..., novideo=<optimized out>)
    at src/ReverseManager.cc:327
#9  0x00000000004552d6 in openmsx::ReverseManager::goTo (
    this=this@entry=0x18bb950, tokens=...) at src/ReverseManager.cc:317
#10 0x0000000000456c6e in openmsx::ReverseManager::ReverseCmd::execute (
    this=0x18bb990, tokens=..., result=...) at src/ReverseManager.cc:1016
#11 0x000000000047bbc5 in openmsx::ProxyCmd::execute (this=<optimized out>, 
    tokens=..., result=...) at src/commands/ProxyCommand.cc:39
#12 0x0000000000478cc8 in openmsx::Interpreter::commandProc (
    clientData=0x18bba80, interp=0x1878ea0, objc=3, objv=<optimized out>)
    at src/commands/Interpreter.cc:171
#13 0x00007fbf76e079ca in ?? () from /usr/lib/x86_64-linux-gnu/libtcl8.5.so
#14 0x00007fbf76e4dd14 in ?? () from /usr/lib/x86_64-linux-gnu/libtcl8.5.so
```

This seems to be another regression caused by calling deliverEvents, this time while calculating the tth hash.

**Comment by MBilderbeek** [comment]
Fixed by Wouter in commit 2f3588b06a92daa1ee6de0f94f7ff544fb71cdb0
