### ISSUE TITLE
If no video driver available, openMSX crashes

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1460]
On a RPi without desktop with openMSX 16.0:
```
$ openmsx
info: SRAM file cbios-msx2+.cmos not found, assuming blank SRAM content.
warning: Couldn't activate renderer SDLGL-PP: Could not create window: Could not load EGL library
Trying to switch to SDL renderer instead...
Segmentation fault
```

From gdb:
```
(gdb) run
Starting program: /usr/bin/openmsx
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ff5ecff00 (LWP 7962)]
[New Thread 0x7ff56cef00 (LWP 7963)]
info: SRAM file cbios-msx2+.cmos not found, assuming blank SRAM content.
[New Thread 0x7ff4e17f00 (LWP 7964)]
warning: Couldn't activate renderer SDLGL-PP: SDL init failed (32): displayIndex must be in the range 0 - -1
Trying to switch to SDL renderer instead...
warning: Couldn't activate renderer SDL: SDL init failed (32): displayIndex must be in the range 0 - -1
Trying to decrease scale_factor setting from 2 to 1...
[Thread 0x7ff56cef00 (LWP 7963) exited]
Uncaught exception: SDL init failed (32): displayIndex must be in the range 0 - -1 (and I have no other ideas to try...)
[Thread 0x7ff5ecff00 (LWP 7962) exited]
[Thread 0x7ff4e17f00 (LWP 7964) exited]
[Inferior 1 (process 7957) exited with code 01]
```

Test with my devel build:
```
$ SDL_VIDEODRIVER=fb openmsx
warning: Couldn't activate renderer SDLGL-PP: SDL init failed (32): fb not available
Trying to switch to SDL renderer instead...
warning: Couldn't activate renderer SDL: SDL init failed (32): fb not available
Trying to decrease scale_factor setting from 4 to 3...
warning: Couldn't activate renderer SDL: SDL init failed (32): fb not available
Trying to decrease scale_factor setting from 3 to 2...
warning: Couldn't activate renderer SDL: SDL init failed (32): fb not available
Trying to decrease scale_factor setting from 2 to 1...
terminate called after throwing an instance of 'openmsx::MSXException'
Aborted (core dumped)
```
From gdb:
```
Trying to switch to SDL renderer instead...
warning: Couldn't activate renderer SDL: SDL init failed (32): fb not available
Trying to decrease scale_factor setting from 4 to 3...
warning: Couldn't activate renderer SDL: SDL init failed (32): fb not available
Trying to decrease scale_factor setting from 3 to 2...
warning: Couldn't activate renderer SDL: SDL init failed (32): fb not available
Trying to decrease scale_factor setting from 2 to 1...
terminate called after throwing an instance of 'openmsx::MSXException'

Thread 1 "openmsx" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, 
    signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff7489d2f in __pthread_kill_internal (signo=6, 
    threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff743aef2 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7425472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff769d919 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff76a8e1a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff76a7e89 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff76a85a6 in __gxx_personality_v0 ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff75f6934 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#9  0x00007ffff75f738d in _Unwind_Resume ()
   from /lib/x86_64-linux-gnu/libgcc_s.so.1
#10 0x00005555555f5b8f in openmsx::Display::doRendererSwitch (
    this=<optimized out>) at src/video/Display.cc:305
#11 0x00005555558f954d in std::__do_visit<std::__detail::__variant::__deduce_visit_result<void>, overloaded<openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openmsx::FinishFrameEvent&)>, openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openmsx::SwitchRendererEvent&)>, openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openmsx::MachineLoadedEvent&)>, openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openm--Type <RET> for more, q to quit, c to continue without paging--
sx::ExposeEvent&)>, openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openmsx::FocusEvent&)>, openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openmsx::EventBase&)> >, const std::variant<openmsx::KeyUpEvent, openmsx::KeyDownEvent, openmsx::MouseMotionEvent, openmsx::MouseButtonUpEvent, openmsx::MouseButtonDownEvent, openmsx::MouseWheelEvent, openmsx::JoystickAxisMotionEvent, openmsx::JoystickHatEvent, openmsx::JoystickButtonUpEvent, openmsx::JoystickButtonDownEvent, openmsx::OsdControlReleaseEvent, openmsx::OsdControlPressEvent, openmsx::FocusEvent, openmsx::ResizeEvent, openmsx::FileDropEvent, openmsx::QuitEvent, openmsx::FinishFrameEvent, openmsx::CliCommandEvent, openmsx::GroupEvent, openmsx::BootEvent, openmsx::FrameDrawnEvent, openmsx::BreakEvent, openmsx::SwitchRendererEvent, openmsx::TakeReverseSnapshotEvent, openmsx::AfterTimedEvent, openmsx::MachineLoadedEvent, openmsx::MachineActivatedEvent, openmsx::MachineDeactivatedEvent, openmsx::ExposeEvent, openmsx::MidiInReaderEvent, openmsx::MidiInWindowsEvent, openmsx::MidiInCoreMidiEvent, openmsx::MidiInCoreMidiVirtualEvent, openmsx::Rs232TesterEvent>&> (__visitor=...)
    at /usr/include/c++/12/variant:1750
#12 std::visit<overloaded<openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openmsx::FinishFrameEvent&)>, openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openmsx::SwitchRendererEvent&)>, openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openmsx::MachineLoadedEvent&)>, openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openmsx::ExposeEvent&)>, openmsx::Display::signalEvent(const openmsx::Event&)::<lambda(const openmsx::FocusEvent&)>, openmsx::Display::signalEvent(const openmsx::Event...
```

It would be nice if this fatal exception could be handled nicer. One way is like attached patch... @m9710797 what do you think?
[avoid_crash_without_video.patch.txt](https://github.com/openMSX/openMSX/files/9998159/avoid_crash_without_video.patch.txt)

**Comment by MBilderbeek** [comment]
Fixed in 862166911d1f9f87500d89b4f15bcc8bacc94308.

If you really want to start up without a renderer, you can use -control stdio (and use the stdin/stdout to give openMSX commands).
