### ISSUE TITLE
diskmanipulator export command causes crash

### ISSUE THREAD

**Issue by denjhang** [openMSX/openMSX#1473]
https://user-images.githubusercontent.com/61811583/210693731-6510cd10-e3f3-468e-b941-b124fe8a39b8.mp4

[OPX-MPK.zip](https://github.com/openMSX/openMSX/files/10349037/OPX-MPK.zip)
I want to export the files in OPX-MPK.DSK, but openmsx crashes.

**Comment by MBilderbeek** [comment]
I can reproduce it, if I create a directory 'test' first and use `diskmanipulator export hda test` to trigger.

Simple bt:
```
#0  0x00007ffff7bcf8dc in Tcl_GetStringFromObj ()
   from /lib/x86_64-linux-gnu/libtcl8.6.so
#1  0x000055555569ad21 in openmsx::TclObject::getString (
    this=this@entry=0x555555d4e3f0) at src/commands/TclObject.cc:123
#2  0x0000555555798538 in openmsx::DiskManipulator::exprt (
    this=<optimized out>, driveData=..., dirname="test", lists=...)
    at src/fdc/DiskManipulator.cc:537
#3  0x00005555557992c9 in openmsx::DiskManipulator::execute (
    this=0x555555cffba0, tokens=..., result=...)
    at src/fdc/DiskManipulator.cc:159
#4  0x0000555555697362 in openmsx::Interpreter::commandProc (
    clientData=0x555555cffba0, interp=0x555555d40ad0, objc=4, 
    objv=0x555555d4e3d0) at src/commands/Interpreter.cc:190
#5  0x00007ffff7b020c8 in TclNRRunCallbacks ()
   from /lib/x86_64-linux-gnu/libtcl8.6.so
#6  0x00007ffff7b033d3 in ?? () from /lib/x86_64-linux-gnu/libtcl8.6.so
#7  0x00007ffff7b02e43 in Tcl_EvalEx () from /lib/x86_64-linux-gnu/libtcl8.6.so
#8  0x00007ffff7b040d5 in Tcl_Eval () from /lib/x86_64-linux-gnu/libtcl8.6.so
#9  0x00005555556973d7 in openmsx::Interpreter::execute (
    this=this@entry=0x555555d1b440, command=...)
    at src/commands/Interpreter.cc:219
#10 0x000055555568da4b in openmsx::GlobalCommandController::executeCommand (
    this=0x555555d1b400, command=..., connection_=connection_@entry=0x0)
```

**Comment by grauw** [comment]
The above stack trace is probably due to memory corruption. The real issue occurs earlier, and it triggers the asserts I added in https://github.com/openMSX/openMSX/commit/b70d8ad4c615a54eacd871f81ac83201f6522b2a.

See https://github.com/openMSX/openMSX/commit/f3ea70a6133314bbd825d1b0fc48b1a3f32e7724 for the description of the problem and the fix.
