### ISSUE TITLE
Crash when loading old replays

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1502]
E.g. load this replay with current openMSX: https://tasvideos.org/3188S (also attached).
[submission3188.zip](https://github.com/openMSX/openMSX/files/11270920/submission3188.zip)

```
$ openmsx zggzdydpscrimpehmogimprov.omr         
warning: Loading an old savestate: the timing of the CPU-VDP communication emulation has changed. This may cause synchronization problems in replay.
openmsx: src/memory/RomBlocks.cc:145: void openmsx::RomBlocks<BANK_SIZE_>::serialize(Archive&, unsigned int) [with Archive = openmsx::XmlInputArchive; unsigned int BANK_SIZE_ = 8192]: Assertion `false' failed.
Aborted (core dumped)
```

stack strace:

```
hread 1 "openmsx" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, 
    no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, 
    signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff7489d2f in __pthread_kill_internal (signo=6, 
    threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff743aef2 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7425472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7425395 in __assert_fail_base (
    fmt=0x7ffff7599a70 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x5555568d78b9 "false", 
    file=file@entry=0x5555568d7394 "src/memory/RomBlocks.cc", 
    line=line@entry=145, 
    function=function@entry=0x5555568d7bb8 "void openmsx::RomBlocks<BANK_SIZE_>::serialize(Archive&, unsigned int) [with Archive = openmsx::XmlInputArchive; unsigned int BANK_SIZE_ = 8192]") at ./assert/assert.c:92
#5  0x00007ffff7433df2 in __GI___assert_fail (
    assertion=0x5555568d78b9 "false", 
    file=0x5555568d7394 "src/memory/RomBlocks.cc", line=145, 
    function=0x5555568d7bb8 "void openmsx::RomBlocks<BANK_SIZE_>::serialize(Archive&, unsigned int) [with Archive = openmsx::XmlInputArchive; unsigned int BANK_SIZE_ = 8192]") at ./assert/assert.c:101
#6  0x0000555555e37c04 in openmsx::RomBlocks<8192u>::serialize<openmsx::XmlInputArchive> (this=0x555558b6d140, ar=...) at src/memory/RomBlocks.cc:145
--Type <RET> for more, q to quit, c to continue without paging-- 
#7  0x0000555555e30a93 in openmsx::serialize<openmsx::XmlInputArchive, openmsx::RomBlocks<8192u> > (
    ar=..., t=..., version=1) at src/serialize_core.hh:55
#8  0x0000555555e2fe06 in openmsx::ClassLoader<openmsx::RomBlocks<8192u> >::operator()<openmsx::XmlInputArchive, std::tuple<> >(openmsx::XmlInputArchive&, openmsx::RomBlocks<8192u>&, std::tuple<>, int, int) (this=0x7fffffffb207, ar=..., t=..., id=-1, version=1) at src/serialize_core.hh:610
#9  0x0000555555e2f598 in openmsx::InputArchiveBase<openmsx::XmlInputArchive>::serialize<openmsx::RomBlocks<8192u> > (this=0x7fffffffc1e0, tag=0x5555568d5fba "Rom8kBBlocks", t=...) at src/serialize.hh:583
#10 0x0000555555e88c85 in openmsx::ArchiveBase<openmsx::XmlInputArchive>::serializeBase<openmsx::RomBlocks<8192u>, openmsx::RomKonami> (this=0x7fffffffc1e0, t=...) at src/serialize.hh:96
#11 0x0000555555e88af8 in openmsx::RomKonami::serialize<openmsx::XmlInputArchive> (
    this=0x555558b6d140, ar=...) at src/memory/RomKonami.cc:65
#12 0x0000555555e898fc in openmsx::serialize<openmsx::XmlInputArchive, openmsx::RomKonami> (ar=..., 
    t=..., version=1) at src/serialize_core.hh:55
#13 0x0000555555e89390 in openmsx::ClassLoader<openmsx::RomKonami>::operator()<openmsx::XmlInputArchive, std::tuple<> >(openmsx::XmlInputArchive&, openmsx::RomKonami&, std::tuple<>, int, int) (
    this=0x7fffffffb31f, ar=..., t=..., id=154, version=1) at src/serialize_core.hh:610
#14 0x0000555555e88f69 in openmsx::PolymorphicInitializerRegistry<openmsx::XmlInputArchive>::registerClass<openmsx::RomKonami>(char const*)::{lambda(openmsx::XmlInputArchive&, void*, unsigned int)#1}::operator()(openmsx::XmlInputArchive&, void*, unsigned int) const (__closure=0x5555571988c8, ar=..., 
    v=0x555558b6d140, id=154) at src/serialize_meta.hh:229
#15 0x0000555555e8a44b in std::__invoke_impl<void, openmsx::PolymorphicInitializerRegistry<openmsx::XmlInputArchive>::registerClass<openmsx::RomKonami>(char const*)::{lambda(openmsx::XmlInputArchive&, void*, unsigned int)#1}&, openmsx::XmlInputArchive&, void*, unsigned int>(std::__invoke_other, openmsx::PolymorphicInitializerRegistry<openmsx::XmlInputArchive>::registerClass<openmsx::RomKonami>(char const*)::{lambda(openmsx::XmlInputArchive&, void*, unsigned int)#1}&, openmsx::XmlInputArchive&, void*&&, unsigned int&&) (__f=...) at /usr/include/c++/12/bits/invoke.h:61
#16 0x0000555555e89f85 in std::__invoke_r<void, openmsx::PolymorphicInitializerRegistry<openmsx::XmlInputArchive>::registerClass<openmsx::RomKonami>(char const*)::{lambda(openmsx::XmlInputArchive&, void*, unsigned int)#1}&, openmsx::XmlInputArchive&, void*, unsigned int>(openmsx::PolymorphicInitializerRegistry<openmsx::XmlInputArchive>::registerClass<openmsx::RomKonami>(char const*)::{lambda(openmsx::XmlInputArchive&, void*, unsigned int)#1}&, openmsx::XmlInputArchive&, void*&&, unsigned int&&) (__fn=...)
    at /usr/include/c++/12/bits/invoke.h:111
#17 0x0000555555e899b4 in std::_Function_handler<void (openmsx::XmlInputArchive&, void*, unsigned int), openmsx::PolymorphicInitializerRegistry<openmsx::XmlInputArchive>::registerClass<openmsx::RomKonami>(char const*)::{lambda(openmsx::XmlInputArchive&, void*, unsigned int)#1}>::_M_invoke(std::_Any_data const&, openmsx::XmlInputArchive&, void*&&, unsigned int&&) (__functor=..., __args#0=..., 
    __args#1=@0x7fffffffb448: 0x555558b6d140, __args#2=@0x7fffffffb444: 154)
    at /usr/include/c++/12/bits/std_function.h:290
#18 0x00005555557d6451 in std::function<void (openmsx::XmlInputArchive&, void*, unsigned int)>::operator()(openmsx::XmlInputArchive&, void*, unsigned int) const (this=0x5555571988c8, __args#0=..., 
    __args#1=0x555558b6d140, __args#2=154) at /usr/include/c++/12/bits/std_function.h:591
#19 0x00005555557d36e3 in openmsx::PolymorphicInitializerRegistry<openmsx::XmlInputArchive>::init (
    tag=0x55555678aecf "device", ar=..., t=0x555558b6d140) at src/serialize_meta.cc:126
#20 0x0000555555854e28 in openmsx::InputArchiveBase<openmsx::XmlInputArchive>::serializePolymorphic<openmsx::MSXDevice> (this=0x7fffffffc1e0, tag=0x55555678aecf "device", t=...) at src/serialize.hh:599
#21 0x0000555555850320 in openmsx::HardwareConfig::serialize<openmsx::XmlInputArchive> (
    this=0x5555589fcfc0, ar=..., version=1) at src/config/HardwareConfig.cc:504
#22 0x00005555556ddeaf in openmsx::serialize<openmsx::XmlInputArchive, openmsx::HardwareConfig> (
    ar=..., t=..., version=1) at src/serialize_core.hh:55
#23 0x00005555556dbed4 in openmsx::ClassLoader<openmsx::HardwareConfig>::operator()<openmsx::XmlInputArchive, std::tuple<> >(openmsx::XmlInputArchive&, openmsx::HardwareConfig&, std::tuple<>, int, int) (
    this=0x7fffffffb71f, ar=..., t=..., id=138, version=1) at src/serialize_core.hh:610
#24 0x00005555556d8461 in openmsx::NonPolymorphicPointerLoader<openmsx::HardwareConfig>::operator()<openmsx::XmlInputArchive, std::tuple<std::reference_wrapper<openmsx::MSXMotherBoard> > > (
    this=0x7fffffffb7ff, ar=..., id=138, globalArgs=std::tuple containing = {...})
    at src/serialize_core.hh:633
```

**Comment by MBilderbeek** [comment]
Fixed by @m9710797 in f05c23a703c4e7fadc18592631b3980255d611e2 - confirmed. Thanks!
